services:
  backtester-worker:
    container_name: backtester-worker
    image: demyanishenko/algotrade-backtester
    pull_policy: always
    depends_on:
      - strategies-go
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network


  strategies-go:
    container_name: backtester-worker-strategies-go
    image: demyanishenko/algotrade-strategies-go
    restart: unless-stopped
    pull_policy: always
    env_file:
      - .env
    networks:
      - app-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: backtester-worker-strategies-go backtester-worker --interval 60 --cleanup

networks:
  app-network:
